### ISSUE TITLE
Segfault in smithay-clipboard -- dep needs to be bumped to 0.6.2 or later

### ISSUE THREAD

**Issue by FireyFly** [alacritty/copypasta#26]
After a system update, I ran into segfaults from `smithay-clipboard`:

> `smithay-clipboa[11623]: segfault at 56225dbf8136 ip 00007fe75d34cd10 sp 00007fe74de0b598 error 4 in libwayland-client.so.0.3.0[7fe75d348000+6000]`

The relevant segfault [has been fixed upstream][1] and the v0.6.2 release appears to include a patch for it. After that it took me a bit of digging around to figure out what pulls it into my system, but eventually I realised it's from alacritty via copypasta.

Should be straightforward to bump the dependency as far as I can tell. Bumping it, doing a release of copypasta & bumping the copypasta dep in alacritty so it's ready for the next alacritty release would be appreciated!

[1]: https://github.com/Smithay/smithay-clipboard/pull/31

**Comment by chrisduerr** [comment]
There's no need to update copypasta and this is already tracked in Alacritty.
