### ISSUE TITLE
Is Wayland supported by default, or is additional logic required for this?

### ISSUE THREAD

**Issue by timvisee** [alacritty/copypasta#27]
It is unclear to me how Wayland support works.

The crate provides the `wayland_clipboard` module for interacting with the Wayland clipboard. The `copypasta::ClipboardContext` definition always provides a X11 context (on Linux) though.

So, does this mean Wayland isn't _automatically_ supported? And does this mean that adding Wayland support requires additional logic by the implementer to determine at runtime whether to construct an X11 or a Wayland clipboard context, including figuring out the Wayland display pointer?

**Comment by chrisduerr** [comment]
It's impossible to do this automatically. You require a display handle from your window to access the clipboard on Wayland.
