### ISSUE TITLE
Feature Request: Android support via Termux.

### ISSUE THREAD

**Issue by 5c0tt-b0t** [alacritty/copypasta#28]
Hi! a text editor I use on my Android tablet via Termux, uses this lib, so I am unable to copy/paste.
I was wondering if you would be kind enough to support this OS also?
The two commands are:
- termux-clipboard-set
- termux-clipboard-get

They work just like `xclip` but take no extra args, just whatever you want on the clipboard, kinda like `pbcopy`.
Thank you.

**Comment by chrisduerr** [comment]
Termux is not an appropriate clipboard backend. If anything one would have to use Android's system facilities.

And I doubt anyone cares enough about mobile platforms to implement and maintain this implementation.
