### ISSUE TITLE
docs bug

### ISSUE THREAD

**Issue by erikh** [alacritty/copypasta#30]
If you don't use `copypasta::{ClipboardContext, ClipboardProvider}` your example is missing the trait in scope in a lot of situations I think? This is what I had to do with my own use of this library.

HTH! Thank you for the great work.

**Comment by chrisduerr** [comment]
Which example are you talking about?

**Comment by erikh** [comment]
the one in the repository readme

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by chrisduerr** [comment]
You're correct. Do you want to fix this yourself?

**Comment by erikh** [comment]
really don't have much time right now, just wanted to make a note of it to assist. I'm sure this ticket will be enough for plenty.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
