### ISSUE TITLE
request to feature gate backends

### ISSUE THREAD

**Issue by coderedart** [alacritty/copypasta#35]
I'm using this on linux and its great. but i don't actually care about wayland at all (as i use some x11 commands directly). every time i see a lot of compilation time taken by wayland dependencies, it feels really sad. can there be feature gates for separate backends ? other platforms only have single backend, so it works out fine when gated by the platform. but for linux, i think it would be useful if wayland (or maybe even x11) are feature gated to reduce compile times.

**Comment by chrisduerr** [comment]
https://github.com/alacritty/copypasta/blob/master/Cargo.toml#L15

**Comment by coderedart** [comment]
I'm so sorry. I just checked docs.rs and i forgot to actually check the src. https://docs.rs/crate/copypasta/0.7.1/features doesn't list anything for some reason :(

**Comment by chrisduerr** [comment]
> Feature flags are not available for this release because it was built before features were collected by docs.rs.
