### ISSUE TITLE
Please document Wayland usage

### ISSUE THREAD

**Issue by piegamesde** [alacritty/copypasta#38]
The main selling feature for this crate is its Wayland support. However, the instructions on how to actually use it under Wayland are unclear. From #27 I know that it still defaults to XOrg on Linux and some manual intervention is required.

I think some kind of `new()` method that simply builds a matching clipboard provider for the current system would really help here too.

**Comment by chrisduerr** [comment]
All you have to do is open the documentation and right on the landing page you'll find the wayland module. If you don't want to read the docs that's on you.

**Comment by piegamesde** [comment]
Yeah thank you I've read the documentation and found that method. IMO my points above still stand though.
