### ISSUE TITLE
Proposal to change the x11 clipboard implementation

### ISSUE THREAD

**Issue by MarcusGrass** [alacritty/copypasta#45]
Hi,

I've been working a bit with [x11rb](https://github.com/psychon/x11rb) for interfacing with x11 without any c-library dependencies.
Currently [x11-clipboard](https://github.com/quininer/x11-clipboard) uses [the xcb-crate](https://docs.rs/xcb/latest/xcb/) which is rust bindings for libxcb. x11rb is like libxcb implemented in rust and avoids the c-library dependencies as well as unsoundness issues. I'm considering creating a fork of x11-clipboard which uses that implementation instead. 

If I did, would you be okay with using that instead in this crate?

**Comment by chrisduerr** [comment]
Depending on a new untested rewrite that will also go unmaintained in two weeks doesn't exactly sound like a great improvement. So far `x11-clipboard` in its latest version works relatively well at least, I'm sure upstream would also be happy to accept any patches that are net improvements.

**Comment by MarcusGrass** [comment]
I'm sorry that you believe that's the case.  

I did have a look and the API could be the same except for some Errors and exposing the dependency crate, I originally thought that some structural changes would be necessary but it's almost exclusively plumbing, for this crate that change would be a single line change on a use statement so I'll see if I can PR it there!

**Comment by chrisduerr** [comment]
APIs can change, there's a reason why breaking semver versions exist. I'm sure @quininer would appreciate any help with maintaining x11-clipboard.
