### ISSUE TITLE
Improve/more specific error if TTY/CI?

### ISSUE THREAD

**Issue by xliiv** [alacritty/copypasta#48]
[the hello world example](https://github.com/alacritty/copypasta/blob/c0203bb46046115c253cf4fcf1a957a88b1bfc89/examples/hello_world.rs) gets the following error

```shell
    Finished dev [unoptimized + debuginfo] target(s) in 0.03s
     Running `target/debug/examples/hello_world`
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: XcbConn(ClosedParseErr)', examples/hello_world.rs:4:43
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

If you recon it's pointless, feel free to close the issue.
 
I'm just sharing my finding and I'm curious what you think.

**Comment by chrisduerr** [comment]
I don't think that's particularly unexpected. Running `copypasta` examples in the TTY is already unusual so you should be expecting a failure anyway. Running it in the CI seems completely pointless.

With that considered, I think users should be well prepared what an unwrap on some `XcbConn` error thing probably means exactly what you'd expect to happen when you're running it without any display server.

**Comment by xliiv** [comment]
Makes sense, thanks for sharing good reasoning. :+1:
