### ISSUE TITLE
Listening for changes MacOS

### ISSUE THREAD

**Issue by DandrewsDev** [alacritty/copypasta#54]
From what I can tell there isnt an existing way to listen for changes right now. Would that be possible to add?
Is there a good or recommended workaround currently? I could go the route of polling, and track the last know new item and compare.

What would be the best way to go about continually checking for new items being added in the background?

**Comment by chrisduerr** [comment]
Listening for changes of what?

**Comment by kchibisov** [comment]
I think they want some sort of clipboard manager like thing to spy on clipboard and keep it around or sort of.

I don't think that clipboard managers are in scope.

**Comment by chrisduerr** [comment]
Yeah I have no interest in adding that myself.

**Comment by Lurk** [comment]
When I was researching this topic (two years ago, so it may not be valid anymore), macOS had no way to subscribe to clipboard changes. Everybody was querying the clipboard in a loop.
