### ISSUE TITLE
clipboard-win dependency is outdated

### ISSUE THREAD

**Issue by rhysd** [alacritty/copypasta#65]
Currently this crate depends on clipboard-win v3 but the version is quite old. clipboard-win v4 was released 3 years ago and the latest version v4.5.0 was released 11 months ago. The implementation would be stable.

https://crates.io/crates/clipboard-win/versions

I want to use more recent version of clipboard-win through copypasta crate for [this issue](https://github.com/rhysd/tui-textarea/issues/50). Specifically, clipboard-win v3 does not allow setting an empty string to clipboard. And the limitation was removed at [clipboard-win v4.4.0](https://github.com/DoumanAsh/clipboard-win/commit/4a5b7aa071aed66e9560d112eb44b89e8644f44e). I need this change for resolving the issue.

**Comment by chrisduerr** [comment]
Patches welcome, no maintainer owns Windows hardware so it certainly receives less focus.
