### ISSUE TITLE
update x11-clipboard to 0.9.2

### ISSUE THREAD

**Issue by 0323pin** [alacritty/copypasta#69]
Hi,

Could you please update the `x11-clipboard` dependency to the newly released v0.9.2?
See, https://github.com/quininer/x11-clipboard/issues/48 for the reason

Thanks!

**Comment by kchibisov** [comment]
sure, send a patch.

**Comment by kchibisov** [comment]
Ah, wait, it's copypasta. There's no need to patch it here since it's _compatible_.

**Comment by 0323pin** [comment]
> Ah, wait, it's copypasta. There's no need to patch it here since it's _compatible_.

So, do you want me to do something or, not?

**Comment by kchibisov** [comment]
If you want that fixed in alacritty you should send patch to it, but if you coming from other background you don't need any action to do.

**Comment by 0323pin** [comment]
Well, the end goal is, of course, to be able to build Alacritty again.
So, bump `x11-clipboard` dependency to 0.9.2 -> bump `copypasta` to 0.10.2 -> bump that dependency in `alacritty`.

Am I missing something here?

**Comment by kchibisov** [comment]
you can just bump straight in alacritty.

**Comment by 0323pin** [comment]
> you can just bump straight in alacritty.

Thanks for https://github.com/alacritty/alacritty/pull/7800

When I tried this locally, it complained that `x11-clipboard`-0.9.2 did not satisfy the dependency of `copypasta`-0.10.1
That's why, I started here.

But, I'll kick start a new `alacritty` build once #7800 gets merged.

**Comment by kchibisov** [comment]
unless the crate was pinned with `=` it'll pick the latest versions, though, if you do offline builds you need to pull the crate and also update the lock file.

**Comment by 0323pin** [comment]
Yes, I do all my builds inside the pkgsrc infrastructure and, these must be offline.

I like this approach, as it controls the checksums of all the crates which, at least gives some security  against modified or, corrupted files.

I've been running my own builds from the git-HEAD of `alacritty` this way for nearly two years now.

**Comment by kchibisov** [comment]
yeah, but I'm saying that you should specify that you pulls 0.9.2 somehow, not sure how it's done though, in gentoo we just pull packages and then build offline or specify crates tars and pull.

**Comment by 0323pin** [comment]
I'm sure it will work now.
As said, I'll start a new build soon ...

You know what, I'll just kick start one from your branch right now :)

**Comment by 0323pin** [comment]
@kchibisov All good now, thanks :+1: 

![2024-03-02-122510_837x522_scrot](https://github.com/alacritty/copypasta/assets/90570748/bf53858b-283a-45a2-998a-825d30c81638)
