### ISSUE TITLE
copypasta does not build for visionos

### ISSUE THREAD

**Issue by coolbluewater** [alacritty/copypasta#76]
Copypasta does not build for the recently added `aarch64-apple-visionos` target.
Running:

```shell
RUSTFLAGS="-Awarnings" cargo +nightly build --target aarch64-apple-visionos -Zbuild-std
```
produces a bunch of errors that are quite easy to fix, mostly due to missing `cfg` cases for `visionos`.

**Comment by chrisduerr** [comment]
That's because it's not a supported OS. If you want to add support for it, it likely shouldn't be too difficult. But at the first hint of visionOs actually being different than macOs, it will get nuked.
